Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

# I can correct It by -a
Style/FrozenStringLiteralComment:
  Safe: true

# About ABC http://wiki.c2.com/?AbcMetric
Metrics/AbcSize:
  Enabled: false

AllCops:
  NewCops: disable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*' # For CI broken
